var LongNamespacedCoreObject=Basis={
   hasClass:function(target,classValue){var pattern=new RegExp('(^| )'+classValue+'( |$)');return(pattern.test(target.className));},
   addClass:function(target,classValue){if(!Basis.hasClass(target,classValue)){target.className+=(target.className==='')?classValue:(' '+classValue);}},
   removeClass:function(target,classValue){if(Basis.hasClass(target,classValue)){var pattern=new RegExp('(^| )'+classValue+'( |$)');target.className=target.className.replace(pattern,'$1').replace(/ $/,'');}},
   getElementsByClass:function(classValue,parent){var matchedElements=[],allElements;if(document.querySelectorAll){allElements=(arguments.length>1)? parent.querySelectorAll('.'+classValue):document.querySelectorAll('.'+classValue);matchedElements=Basis.realArray(allElements);}/*favourite browzer*/else{allElements=(arguments.length>1)?parent.getElementsByTagName('*'):document.body.getElementsByTagName('*');var pattern=new RegExp('(^| )'+classValue+'( |$)'),i,l=allElements.length;for(i=0;i<l;i++){if(pattern.test(allElements[i].className)){matchedElements[matchedElements.length]=allElements[i];}}}return matchedElements;},
   getElementsByAttr:function(el,attr,value,parent){var matchedElements=[],allElements;if(document.querySelectorAll){allElements=(arguments.length>3)?parent.querySelectorAll(el+'['+attr+'="'+value+'"]'):document.querySelectorAll('['+attr+'='+value+']');matchedElements=Basis.realArray(allElements);}/*favourite browzer*/else{allElements=(arguments.length>3)?parent.getElementsByTagName(el):document.body.getElementsByTagName(el);var i,l=allElements.length;for(i=0;i<l;i++){if(allElements[i].getAttribute(attr)===value){matchedElements[matchedElements.length]=allElements[i];}}}return matchedElements;},
   insertAfter:function(child,reference){var sibling=reference.nextSibling,action=sibling?reference.parentNode.insertBefore(child,sibling):reference.parentNode.appendChild(child);},
   getNextSibling:function(target){var sibling=target.nextSibling;while(sibling.nodeType==3){sibling=sibling.nextSibling;}return sibling;},
   getPrevSibling:function(target){var sibling=target.previousSibling;while(sibling.nodeType==3){sibling=sibling.previousSibling;}return sibling;},
   getChildren:function(parent){var children=parent.childNodes,arr=[],i,l=children.length;for(i=0;i<l;i++){var child=children[i];if(child.nodeType==1){arr.push(child);}}return arr;},
   getSiblings:function(target,parent){var sibs=Basis.getChildren(parent),arr=[],i,l=sibs.length;for(i=0;i<l;i++){var sibling=sibs[i];if(sibling!=target){arr.push(sibling);}}return arr;},
   setAttributes:function(target, hash){for(var attribute in hash){if(hash.hasOwnProperty(attribute)){if(attribute==='text'){target.appendChild(document.createTextNode(hash[attribute]));continue;}/*DOM1 dot-notation often safest, but misses new stuff;IE pukes on created inputs/buttons.type*/if(attribute.indexOf('aria')===0||attribute==='role'||attribute==='type'){target.setAttribute(attribute,hash[attribute]);continue;}if(attribute==='width'||attribute==='height'||attribute==='display'){target.style[attribute]=hash[attribute];continue;}target[attribute]=hash[attribute];}}},
   isChild:function(target,parent){while((target=target.parentNode)&&target!==parent);return !!target;},
   sallyForth:function(list,fn){var len=list.length;for(var i=0;i<len;i++){fn(list[i]);}},
   realArray:function(list){var arr=[],len=list.length;for(var i=0;i<len;i++){arr.push(list[i]);}return arr;},
/*DOMContentReadies*/
   start:function(fn){var ranAlready=false;function ready(){if(ranAlready){return;}ranAlready=true;fn();}Basis.addDOMListener(ready,ranAlready);}
};//end object
/*w3c*/
if(document.addEventListener){
  Basis.addEventListener   =function(target,type,listener){target.addEventListener(type,listener,false);};
  Basis.addDOMListener     =function(ready){document.addEventListener('DOMContentLoaded',ready,false);/* !DOMContentLoaded support*/window.addEventListener('load',ready,false);};
  Basis.removeEventListener=function(target,type,listener){target.removeEventListener(type,listener,false);};
  Basis.preventDefault     =function(event){event.preventDefault();};
  Basis.stopPropagation    =function(event){event.stopPropagation();};}
/* IE down to 7 */
else if(document.attachEvent){
  Basis.addEventListener=function(target,type,listener){if(Basis._findListener(target,type,listener)!= -1){return;}var listener2=function(){var event=window.event;if(Function.prototype.call){listener.call(target,event);}else{target._currentListener=listener;target._currentListener(event);target._currentListener=null;}};target.attachEvent('on'+type,listener2);var listenerRecord={target:target,type:type,listener:listener,listener2:listener2},targetDocument=target.document||target,targetWindow=targetDocument.parentWindow,listenerId='l'+Basis._listenerCounter++;if(!targetWindow._allListeners){targetWindow._allListeners={};}targetWindow._allListeners[listenerId]=listenerRecord;if(!target._listeners){target._listeners=[];}target._listeners[target._listeners.length]=listenerId;if(!targetWindow._unloadListenerAdded){targetWindow._unloadListenerAdded=true;targetWindow.attachEvent('onunload',Basis._removeAllListeners);}};Basis.tryScroll=function(ready){try{document.documentElement.doScroll('left');ready();}catch(e){setTimeout(Basis.tryScroll,10);}};Basis.addDOMListener=function(ready,ranAlready){if(document.documentElement.doScroll) {if(ranAlready){return;}Basis.tryScroll(ready);}/*if no doScroll support*/window.attachEvent('onload',ready);};Basis.removeEventListener=function(target,type,listener){var listenerIndex=Basis._findListener(target,type,listener);if(listenerIndex== -1){return;}var targetDocument=target.document||target,targetWindow=targetDocument.parentWindow,listenerId=target._listeners[listenerIndex],listenerRecord=targetWindow._allListeners[listenerId];target.detachEvent('on'+type,listenerRecord.listener2);target._listeners.splice(listenerIndex,1);delete targetWindow._allListeners[listenerId];};Basis.preventDefault=function(evt){evt=window.event;evt.returnValue=false;};Basis.stopPropagation=function(evt){evt=window.event;evt.cancelBubble=true;};Basis._findListener=function(target,type,listener){var listeners=target._listeners;if(!listeners){return -1;}var targetDocument=target.document||target,targetWindow=targetDocument.parentWindow;for(var i=listeners.length-1;i>=0;i--){var listenerId=listeners[i],listenerRecord=targetWindow._allListeners[listenerId];if(listenerRecord.type==type && listenerRecord.listener==listener){return i;}}return -1;};Basis._removeAllListeners=function(){var targetWindow=this;for(var id in targetWindow._allListeners){if(targetWindow._allListeners.hasOwnProperty(id)){var listenerRecord=targetWindow._allListeners[id];listenerRecord.target.detachEvent('on'+listenerRecord.type,listenerRecord.listener2);delete targetWindow._allListeners[id];}}};Basis._listenerCounter=0;}
